version: '2.1'
services:
  nginx:
    command: nginx
    build: 
      context: ./
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
    depends_on:
      app:
        condition: service_started
    volumes:
      -  .:/data/web-app