version: '2.1'
services:
  app-green:
    environment:
     - NODE_ENV=development
     - PORT=4001
    command: npm start
    build: 
      context: ./
      dockerfile: Dockerfile-app
    ports:
      - "4000:4001"
  nginx-green:
    command: nginx
    build: 
      context: ./
      dockerfile: Dockerfile-nginx
    links:
      - app
    ports:
      - "80:81"
    depends_on:
      app:
        condition: service_started
    volumes:
      -  .:/data/web-app