version: '2.1'
services:
  app:
    command: npm start
    build: 
      context: ./
      dockerfile: Dockerfile-app
    ports:
      - "4001:4001"
    environment:
     - NODE_ENV=development
     - PORT=4001
  nginx:
    command: nginx
    build: 
      context: ./
      dockerfile: Dockerfile-nginx
    links:
      - app
    ports:
      - "80:80"
    depends_on:
      app:
        condition: service_started
    volumes:
      -  .:/data/web-app