version: '2.1'
networks:
  front:
  back:
services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile-app
    ports:
      - "4000:4000"
    networks:
      - back
  nginx:
    build: 
      context: ./
      dockerfile: Dockerfile-nginx
    links:
      - app
    ports:
      - "80:80"
    depends_on:
      app:
        condition: service_started
    volumes:
      -  .:/data/web-app
    networks:
    - front
    - back