FROM node:latest

MAINTAINER Byul <seyul3@gmail.com>

RUN mkdir -p /data/web-app
WORKDIR /data/web-app
ADD ./web-app /data/web-app
RUN npm install && \
    npm install pm2 && \

    

ENV NODE_ENV development

EXPOSE 4000
# CMD ["pm2", "start", "web-app/app.js"]
CMD ["npm", "start"]
