version: '2.1'
services:
  app:
    environment:
     - NODE_ENV=development
     - PORT=4001
    command: npm start
    ports:
      - "4001:4001"
    build: 
      context: ./
      dockerfile: Dockerfile-app
    networks:
      - _default