version: '2.1'
services:
  app-blue:
    environment:
     - NODE_ENV=development
     - PORT=4000
    command: npm start
    build: 
      context: ./
      dockerfile: Dockerfile-app
    ports:
      - "4000:4000"
  nginx-blue:
    command: nginx
    build: 
      context: ./
      dockerfile: Dockerfile-nginx
    links:
      - app-blue
    ports:
      - "80:80"
    depends_on:
      app-blue:
        condition: service_started
    volumes:
      -  .:/data/web-app