version: '2.1'
services:
  app:
    environment:
     - NODE_ENV=development
     - PORT=4001
    command: npm start
    build: 
      context: ./
      dockerfile: Dockerfile-app
    network_mode: "host"