FROM ubuntu:latest
MAINTAINER byul <sebyul3@gmail.com>

RUN apt-get update && \
    apt-get install -y nginx && \
    echo "\ndaemon off;" >> /etc/nginx/nginx.conf && \
    chown -R www-data:www-data /var/lib/nginx

VOLUME ["/data", "/etc/nginx/sites-enabled", "/var/log/nginx"]

WORKDIR /etc/nginx

ADD ./nginx/ /etc/nginx/sites-available/
RUN cd /etc/nginx/sites-available/ && \
    ln -s web-app /etc/nginx/sites-enabled/web-app && \
    rm default

EXPOSE 80
EXPOSE 443