version: '2.1'
services:
  app:
    environment:
     - NODE_ENV=development
     - PORT=4000
    command: npm start
    ports:
      - "4000:4000"
    build: 
      context: ./
      dockerfile: Dockerfile-app