version: '2.1'
services:
  nginx:
    command: nginx
    build: 
      context: ./
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
    volumes:
      -  .:/data/web-app
    network_mode: "host"