FROM node:latest

MAINTAINER Byul <seyul3@gmail.com>

RUN mkdir -p /data/web-app
WORKDIR /data/web-app
ADD ./ /data/web-app
RUN npm install

ENV NODE_ENV development

EXPOSE 4001

CMD ["npm", "start"]
